version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5431/dbJadso
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - dbpg

  dbpg:
    container_name: dbpg
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbJadso
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}