version: '3.9'

services:
  dbpg:
    container_name: dbpg
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbJadso
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}